# name: 'nightly artifacts cleanup'
# on:
#   schedule:
#     - cron: '0 1 * * *' # every night at 1 am UTC

# jobs:
#   delete-artifacts:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: kolpav/purge-artifacts-action@v1
#         with:
#           token: $
#           expire-in: 0days # Set this to 0 to delete all artifacts

name: 'nightly artifacts cleanup'
on:
  schedule:
    - cron: '0 3 * * *' # every night at 4 am UTC

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0days # Setting this to 0 will delete all artifacts